version: 2.1

workflows:
  test-node-workflow:
    jobs:
      - test-node-job

jobs:
  test-node-job:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: node --version
