version: 2.1

workflows:
  test-node-workflow:
    jobs:
      - test-node-job

jobs:
  test-node-job:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run:
        name: Check Node version
        command: node --version
      - run:
         name: Install dependencies
         command: npm install
        
